#!/usr/bin/env bash
# scripts/coverage-full.sh
#
# PHASE 35d: end-to-end coverage pipeline in a single command.
#
# What it does:
#   1. Run ALL tests in the monorepo (turbo run test --force, no cache)
#      so the coverage numbers reflect a fresh test run, not a stale
#      cache.
#   2. Generate per-package lcov files (turbo run coverage).
#   3. Merge them with the repository-owned LCOV tracefile tool.
#   4. Print ONE big ASCII table at the end with:
#        - per-package OWN line coverage (LF/LH from each lcov, OWN files only)
#        - merged line coverage (LF/LH from coverage/merged/lcov.info)
#        - status (PASS / FAIL)
#   5. Exit 0 if every package is at 100% on OWN, 1 otherwise.
#
# The user mandate is 100% per-package OWN coverage. The merged
# report is shown in the table but is NOT a gate — getting it to
# 100% would require 50+ new test files (multi-week scope).
#
# Every producing command must succeed. Coverage is a quality gate, so a
# missing or failed test/merge must never be hidden by a presentation pipe.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# Step 1: run all tests (visible, no cache)
# ---------------------------------------------------------------------------
echo "======================================================================"
echo "  STEP 1/3 — Running all tests (no turbo cache)"
echo "======================================================================"
echo
# Disable turbo cache for tests by using --force. The turbo.json
# `cache: false` on `test` already prevents reuse, but `--force`
# also re-runs any upstream `^build` dependencies.
# Delete only coverage outputs generated by this measurement. Without this
# cleanup, a failed run can accidentally report yesterday's LCOV as green.
rm -rf \
  apps/bot/coverage \
  packages/paper/coverage \
  packages/exchange/coverage \
  packages/core/coverage \
  packages/shared/coverage \
  packages/backtest/coverage \
  packages/backtest-tools/coverage \
  coverage/merged

npx turbo run test --force
echo

# ---------------------------------------------------------------------------
# Step 2: generate per-package lcov (silent — only lcov, no text)
# ---------------------------------------------------------------------------
echo "======================================================================"
echo "  STEP 2/3 — Generating per-package lcov"
echo "======================================================================"
echo
npx turbo run coverage --force
echo

# ---------------------------------------------------------------------------
# Step 3: merge + ONE big table at the end
# ---------------------------------------------------------------------------
echo "======================================================================"
echo "  STEP 3/3 — Coverage report (single table)"
echo "======================================================================"
echo

PACKAGES=(
  "apps/bot"
  "packages/paper"
  "packages/exchange"
  "packages/core"
  "packages/shared"
  "packages/backtest"
  "packages/backtest-tools"
)

# Merge the fresh LCOV files before parsing them. `coverage:merge` is part of
# the gate, so its exit code deliberately propagates under `set -e`.
bun run coverage:merge

# Per-package OWN line coverage (parsed from each lcov directly
# with awk — no `lcov --summary` because the older CI lcov
# suppresses output on the "no data found for functions" warning).
declare -a ROWS=()
PASS=0
TOTAL=0
FAILED=()

# Table layout (column widths):
#   package: 22 chars
#   status:  4 chars
#   lines:   100.0% (NNNNN of NNNNN lines)
HEADER_PACKAGE="Package"
HEADER_STATUS="Stat"
HEADER_LINES="Line coverage"

PAD() { printf "%-${1}s" "$2"; }
NUMFMT() {
  # 19957 of 22117 lines -> "19957 of 22117 lines" (no padding here)
  printf "%s of %s lines" "$1" "$2"
}

# Print header
echo "+ ------------------------ + ------ + ---------------------------------------- +"
echo "| $(PAD 22 "$HEADER_PACKAGE") | $(PAD 4 "$HEADER_STATUS")  | $(PAD 38 "$HEADER_LINES") |"
echo "| ------------------------ | ------ | ---------------------------------------- |"

for pkg in "${PACKAGES[@]}"; do
  TOTAL=$((TOTAL + 1))
  lcov_path="${pkg}/coverage/lcov.info"
  if [ ! -f "$lcov_path" ]; then
    ROWS+=("| $(PAD 22 "$pkg") | $(PAD 4 "N/A")  | $(PAD 38 "no lcov.info") |")
    FAILED+=("$pkg")
    continue
  fi

  # Sum LF/LH across SF: records whose path starts with "src/" (the
  # package's own source root). Cross-package imports have paths
  # like "../../packages/..." or "../<other>/..." and are excluded.
  read -r lf lh < <(awk '
    /^SF:/ { sf = substr($0, 4) }
    /^LF:/ { split($1, a, ":"); if (sf ~ "^src/") lf += a[2] }
    /^LH:/ { split($1, a, ":"); if (sf ~ "^src/") lh += a[2] }
    END { print lf + 0, lh + 0 }
  ' "$lcov_path")

  if [ "${lf:-0}" = "0" ] && [ "${lh:-0}" = "0" ]; then
    ROWS+=("| $(PAD 22 "$pkg") | $(PAD 4 "FAIL")  | $(PAD 38 "no OWN files matched") |")
    FAILED+=("$pkg")
    continue
  fi

  # The percentage is presentation only. Gate on the exact LCOV counters:
  # one decimal place would render 1999/2000 as `100.0%` even though one
  # executable OWN line was not hit.
  line_pct=$(awk -v lf="$lf" -v lh="$lh" 'BEGIN { if (lf > 0) printf "%.1f", (lh * 100.0) / lf; else print "0" }')

  if [ "$lh" -eq "$lf" ]; then
    ROWS+=("| $(PAD 22 "$pkg") | $(PAD 4 "PASS")  | $(PAD 38 "$(printf '%.1f%% (%s of %s lines)' "$line_pct" "$lh" "$lf")") |")
    PASS=$((PASS + 1))
  else
    ROWS+=("| $(PAD 22 "$pkg") | $(PAD 4 "FAIL")  | $(PAD 38 "$(printf '%.1f%% (%s of %s lines)' "$line_pct" "$lh" "$lf")") |")
    FAILED+=("$pkg")
  fi
done

for r in "${ROWS[@]}"; do
  echo "$r"
done

echo "+ ------------------------ + ------ + ---------------------------------------- +"
echo
echo "  Result: ${PASS}/${TOTAL} packages at 100% line coverage on OWN src/ files"
if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "  FAILED: ${FAILED[*]}"
  exit 1
fi
echo "  ✓ All packages at 100% line coverage on OWN src/ files"
exit 0
