#!/usr/bin/env bash
# scripts/install-mm-bot.sh
# ============================================================================
# Postinstall hook: write a bash wrapper for the mm-bot CLI into
# node_modules/.bin/, and ensure the bot is built so the dist artifact
# exists for ad-hoc use.
# ============================================================================
#
# This script bridges TWO bun quirks:
#
#   1. oven-sh/bun#19782 — "bun install does not link workspace binary on
#                          first run, requires second install"
#   2. oven-sh/bun#21989 — "bun doesn't link executables in node_modules/
#                          .bin when [running in a workspace]"
#
# bun does NOT symlink workspace package `bin` entries to the root
# `node_modules/.bin/` after `bun install`, even though npm does. This
# means `mm-bot` (declared as a bin in `apps/bot/package.json`) is
# invisible to the shell out of the box, even though it is fully
# runnable via `bun run`.
#
# Why a wrapper script (and not a plain symlink to src/index.ts)?
# ----------------------------------------------------------------
# `apps/bot/src/index.ts` starts with `#!/usr/bin/env bun`, so a direct
# symlink WOULD work — bun reads the shebang and runs the TS file. But
# the file imports a transitive dep, `protobufjs/minimal.js`, which bun
# resolves through the workspace's `node_modules`. That works fine when
# you launch via `bun run` (bun walks up to find node_modules) but it is
# brittle when a symlinked binary is invoked from a different cwd: bun
# can fail to locate the workspace node_modules.
#
# The wrapper makes resolution deterministic by cd-ing into the project
# root before exec-ing bun, so the workspace's `node_modules` is always
# found. It also gives us a single chokepoint to add `--no-color` or
# future flags without editing the source.
#
# Idempotent: re-running is a no-op when the wrapper is already in place
# with the correct content.

set -u

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BOT_SRC="$ROOT_DIR/apps/bot/src/index.ts"
BOT_DIST="$ROOT_DIR/apps/bot/dist/index.js"
BIN_DIR="$ROOT_DIR/node_modules/.bin"
WRAPPER="$BIN_DIR/mm-bot"

cd "$ROOT_DIR"

# Step 1: ensure node_modules/.bin exists.
if [ ! -d "$BIN_DIR" ]; then
  mkdir -p "$BIN_DIR"
fi

# Step 2: build apps/bot if dist/index.js is missing or older than src/index.ts.
# This is informational — the wrapper uses src/index.ts, not dist/. We
# still want a fresh dist/ around for `bun run mm-bot:built` and for
# the `bin` field to be discoverable.
if [ ! -f "$BOT_DIST" ] || [ "$BOT_SRC" -nt "$BOT_DIST" ]; then
  echo "[install-mm-bot] building apps/bot (dist/index.js missing or stale)..."
  if (cd "$ROOT_DIR/apps/bot" && bun run build); then
    echo "[install-mm-bot] build OK"
  else
    echo "[install-mm-bot] WARNING: build failed; continuing (wrapper uses src/index.ts)" >&2
  fi
fi

# Step 3: write the wrapper if it is missing or stale.
# The wrapper is a thin bash script that:
#   - cd's into the project root so bun can find node_modules
#   - exec's bun with the absolute path to src/index.ts + user args
#   - forwards exit codes transparently via `exec`
#
# We compare against a hash to avoid unnecessary writes (and inode churn
# that would invalidate any tooling watching the file).
EXPECTED='# Auto-generated by scripts/install-mm-bot.sh — DO NOT EDIT.
# Bridges oven-sh/bun#19782 (workspace bin not symlinked by bun install).
# Forwards all CLI args to the mm-bot TypeScript entry point.
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"
exec bun run "$ROOT_DIR/apps/bot/src/index.ts" "$@"
'

if [ -f "$WRAPPER" ] && [ "$(cat "$WRAPPER")" = "$EXPECTED" ]; then
  echo "[install-mm-bot] mm-bot wrapper already up to date"
  exit 0
fi

# If the file exists but is wrong (old symlink, previous version), remove
# it before writing. `>` is intentional (not `>>`) so the content is
# authoritative.
if [ -e "$WRAPPER" ] || [ -L "$WRAPPER" ]; then
  rm -f "$WRAPPER"
fi

cat > "$WRAPPER" <<'WRAPPER_EOF'
# Auto-generated by scripts/install-mm-bot.sh — DO NOT EDIT.
# Bridges oven-sh/bun#19782 (workspace bin not symlinked by bun install).
# Forwards all CLI args to the mm-bot TypeScript entry point.
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"
exec bun run "$ROOT_DIR/apps/bot/src/index.ts" "$@"
WRAPPER_EOF

chmod +x "$WRAPPER"
echo "[install-mm-bot] wrote wrapper: $WRAPPER"

# Phase 52C: also make mm-bot globally available.
REPO_ROOT_FROM_SCRIPT="$(cd "$(dirname "$0")/.." && pwd)"
GLOBAL_SHIM="$REPO_ROOT_FROM_SCRIPT/bin/mm-bot"
if [[ -f "$GLOBAL_SHIM" ]]; then
  chmod +x "$GLOBAL_SHIM"
  echo "[install-mm-bot] made bin/mm-bot executable"
  if [[ ":$PATH:" == *":/usr/local/bin:"* ]]; then
    if ln -sf "$GLOBAL_SHIM" /usr/local/bin/mm-bot 2>/dev/null; then
      echo "[install-mm-bot] symlinked: /usr/local/bin/mm-bot -> $GLOBAL_SHIM"
      echo "[install-mm-bot] ✅ 'mm-bot' is now available globally: $(command -v mm-bot)"
    else
      echo "[install-mm-bot] ⚠️  could not symlink to /usr/local/bin/mm-bot (permission denied?)" >&2
      echo "[install-mm-bot]    Workaround: add '\$REPO_ROOT/bin' to your PATH" >&2
    fi
  else
    echo "[install-mm-bot] ⚠️  /usr/local/bin not in \$PATH — mm-bot won't be globally available" >&2
    echo "[install-mm-bot]    Add to your shell rc: export PATH=\"\$REPO_ROOT/bin:\$PATH\"" >&2
  fi
else
  echo "[install-mm-bot] (skip global shim — bin/mm-bot not present in this checkout)"
fi
